gas_adjustment = 1

[server]
listen_addr = "0.0.0.0:$PF_PORT"
read_timeout = "20s"
verbose_cors = true
write_timeout = "20s"

[[deviation_thresholds]]
base = "USDT"
threshold = "1.5"

[[deviation_thresholds]]
base = "UMEE"
threshold = "1.5"

[[deviation_thresholds]]
base = "ATOM"
threshold = "1.5"

[[currency_pairs]]
base = "UMEE"
providers = [
  "okx",
  "gate",
  "mexc",
]
quote = "USDT"

[[currency_pairs]]
base = "USDT"
providers = [
  "kraken",
  "coinbase",
  "binanceus",
]
quote = "USD"

[[currency_pairs]]
base = "ATOM"
providers = [
  "okx",
  "bitget",
]
quote = "USDT"

[[currency_pairs]]
base = "ATOM"
providers = [
  "kraken",
  "binanceus",
]
quote = "USD"

[account]
address = "$PRICE_FEEDER_ADDRESS"
chain_id = "test"
validator = "$PRICE_FEEDER_VALIDATOR"

[keyring]
backend = "test"
dir = "$UMEE_VAL_KEY_DIR"

[rpc]
grpc_endpoint = "tcp://localhost:$GRPC"
rpc_timeout = "100ms"
tmrpc_endpoint = "http://localhost:$RPC"

[telemetry]
service-name = "price-feeder"
enabled = false
enable-hostname = true
enable-hostname-label = true
enable-service-label = true
type = "prometheus"
global-labels = [["chain-id", "test"]]

[[provider_endpoints]]
name = "binance"
rest = "https://api1.binance.com"
websocket = "stream.binance.com:9443"

[[provider_endpoints]]
name = "osmosisv2"
rest = "https://api.osmo-api.prod.network.umee.cc"
websocket = "api.osmo-api.prod.network.umee.cc"
