gas_adjustment = 1.5
provider_timeout = "5000ms"

[server]
listen_addr = "0.0.0.0:$PF_PORT"
read_timeout = "20s"
verbose_cors = true
write_timeout = "20s"

[[currency_pairs]]
base = "UMEE"
providers = [
"mock",
]
quote = "USDT"

[[currency_pairs]]
base = "ATOM"
providers = [
"mock",
]
quote = "USDC"

[[currency_pairs]]
base = "USDC"
providers = [
"mock",
]
quote = "USD"

[[currency_pairs]]
base = "USDT"
providers = [
"mock",
]
quote = "USD"

[account]
address = "$PRICE_FEEDER_ADDRESS"
chain_id = "test"
validator = "$PRICE_FEEDER_VALIDATOR"

[keyring]
backend = "test"
dir = "$UMEE_VAL_KEY_DIR"

[rpc]
grpc_endpoint = "tcp://localhost:$GRPC"
rpc_timeout = "100ms"
tmrpc_endpoint = "http://localhost:$RPC"

[telemetry]
service-name = "price-feeder"
<<<<<<< HEAD
enabled = true
enable-hostname = true
enable-hostname_label = true
=======
enabled = false
enable-hostname = true
enable-hostname-label = true
>>>>>>> master
enable-service-label = true
type = "prometheus"
global-labels = [["chain-id", "test"]]
