name: Oracle Module
#  Oracle Module workflow tests the oracle module
#  This workflow run on pushes to master, workflow_dispatch & on every pull request
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  oracle-module:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test oracle module
        run: |
          make test-oracle-module
        env:
          IS_PUBLIC: false
